### ISSUE TITLE
BackupPC v4

### ISSUE THREAD

**Issue by sirdemoncze** [HanGhoul/BackupPC-v3-BetterCSS#1]
Hi, are you planning to edit the theme for BackupPC 4?

Thanks for answer ;-).

**Comment by jfreax** [comment]
Hi,

I tried it on v4 and it works without any major problem.

**Comment by dryugo** [comment]
I tried a lot of things to add a logo in the left top, the source code of the page is already showing the img source code so it loads but dont show up. Does anybody know how to accomplish a logo at the left top of backuppc?

**Comment by broadband9** [comment]
Logo is Located here in Centos anyway:

/usr/share/BackupPC/html/logo.gif

replace logo.gif with the correct image for you.

**Comment by broadband9** [comment]
> 
> 
> I tried a lot of things to add a logo in the left top, the source code of the page is already showing the img source code so it loads but dont show up. Does anybody know how to accomplish a logo at the left top of backuppc?

Logo is Located here in Centos anyway:

/usr/share/BackupPC/html/logo.gif

replace logo.gif with the correct image for you.

**Comment by ursus-the-bear** [comment]
Hi. Just stumbled across your CSS, very nicely done, thanks for sharing! I have found a problem that is a deal-breaker - if I select a host on the left-hand drop down, the left menu items (i.e. below the selected host - Browse backups, LOG file, LOG files and Edit Config) are missing. This means I cannot change the config or look at the logs. I did try and fix it myself but my knowledge of CSS is just not good enough! Would you mind having a look at it? Thx.

**Comment by TimonMi** [comment]
Hey, have a look at #2 ([https://github.com/TimonMi/BackupPC-BetterCSS](https://github.com/TimonMi/BackupPC-BetterCSS))
I made a v4-compatible version. Let me know if you have any issues with it :)
